"""Write deep_hedging.ini, PufferLib 5.0's config for the env, from market.py.

The [env] section carries every number hedge.h reads, including the derived
ones (premium, n_vs, k_var), so the C env and market.py cannot drift apart.

    python make_ini.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..'))
from market import BatesConfig  # noqa: E402

ENV = {'w_init': 0.3, 'w_eta': 0.01, 'shaping': 1, 'reward_scale': 0.1, 'seed': 0}


def main():
    cfg = BatesConfig()
    assert cfg.n_steps == 30, 'hedge.h fixes 30 hedging dates (HEDGE_DATES)'
    kw = {**cfg.c_kwargs(), **ENV}
    env = '\n'.join(f'{k} = {float(v)!r}' for k, v in kw.items())
    text = f"""# Generated by make_ini.py from market.py; do not edit by hand.
[base]
env_name = deep_hedging

[vec]
total_agents = 4096

[policy]
hidden_size = 64
num_layers = 2

[env]
{env}

# One episode is one horizon segment of 32 env steps (hedge.h). gamma = 1:
# the objective is the undiscounted terminal loss.
[train]
horizon = 32
gamma = 1.0
gae_lambda = 0.95
minibatch_size = 8192
total_timesteps = 120_000_000
"""
    with open(os.path.join(HERE, 'deep_hedging.ini'), 'w') as f:
        f.write(text)


if __name__ == '__main__':
    main()
